language: php

php:
  - 7.1
  - 7.2
  - 7.3

before_script:
  - phpenv config-rm xdebug.ini

install:
  - composer install --no-interaction
  - wget -O phpunit https://phar.phpunit.de/phpunit-7.phar
  - chmod +x phpunit

script: phpunit -c phpunit.xml tests/