language: php

php:
  - 7.1
  - 7.2
  - 7.3

before_script:
  - phpenv config-rm xdebug.ini

install:
  - composer install --no-interaction
  - wget -O phpunit.phar https://phar.phpunit.de/phpunit-7.phar

script: php phpunit.phar -c phpunit.xml tests/